/** Editorial terminology — tasteful publication voice */
export const publication = {
  featured: "Featured Stories",
  recent: "Recent Entries",
  catalog: "Catalog",
  catalogEyebrow: "Modern Publication",
  catalogDescription:
    "Browse current Bloodsoaked Media writing — filed by year, mood, tag, and category.",
  browseTheShelf: "Browse the Shelf",
  browseArticles: "Browse the Desk",
  viewCatalog: "View Catalog",
  mediaLog: "Media Log",
  mediaLogEyebrow: "Personal Archive",
  collections: "Collections",
  collectionsEyebrow: "Curated Shelves",
  fromTheEditor: "From the Editor",
  currentlyExperiencing: "Currently Experiencing",
  currentlyPlaying: "Currently Playing",
  collectionFeatures: "Collection Features",
  moods: "Browse by Mood",
  moodsEyebrow: "Atmosphere",
  theVault: "The Vault",
  vaultEyebrow: "Permanent Shelf",
  vaultEntry: "Vault Entry",
  vaultPermanent: "Permanent Shelf Space",
  vaultPreservation: "Archived for Preservation",
  authorNote: "From the Desk",
  relatedOnShelf: "You May Also Find This on the Shelf",
  filedUnder: "Filed Under",
  editorsPick: "Editor's Pick",
  latestLogEntry: "Latest Log Entry",
  recentlyCatalogued: "Recently Added to the Collection",
  inTheVault: "In the Vault",
  vaultRotatingNote: "Selections rotate. The shelf is never finished.",
  partOfCollection: (name: string) => `Part of the ${name}`,
  earlierInCatalog: "Earlier in the Catalog",
  laterInCatalog: "Later in the Catalog",
  byline: "Words by",
  theArchives: "The Archives",
  theArchivesEyebrow: "Recovered Artifacts",
  publicationTimeline: "Publication Timeline",
  timelineEyebrow: "Publication Record",
  legacyArchivedFrom: (source: string) => `Archived from ${source}`,
  legacyPreserved: "Preserved Writing",
  restorationNote: "Restoration Note",
  originallyPublished: "Originally Published",
  originalSource: "Original Source",
  archiveEra: "Archive Era",
  archivedOn: "Archived",
  /** Intentional empty-archive copy — no placeholder articles */
  emptyArticles: "No articles currently filed.",
  emptyReviews: "No reviews currently filed.",
  emptyEssays: "No essays currently filed.",
  emptyCatalog:
    "This shelf is awaiting cataloging. Archive space reserved for future entries.",
  emptyShelf: "This shelf is awaiting cataloging.",
  emptyRecent: "Writing in progress. New entries will appear here when filed.",
  emptySearch:
    "No matches in the catalog. Try another term or browse the Media Log and Vault.",
} as const;

export const categoryLabels: Record<string, string> = {
  games: "Games",
  film: "Film",
  television: "Television",
  music: "Music",
  culture: "Culture",
};

export const mediumLabels: Record<string, string> = {
  game: "Game",
  film: "Film",
  television: "Television",
  music: "Music",
  book: "Book",
  culture: "Culture",
};
