/**
 * Archive Workbench voice — curator operations room.
 *
 * Quiet stewardship language. Never SaaS, inventory software, or
 * product-management copy. Prefer Holding, Accession, Filed, Archive,
 * Artifact, Stewardship, Documentation, Record.
 */

export const workbenchVoice = {
  name: "Archive Workbench",
  eyebrow: "Bloodsoaked Media · Stewardship",
  introduction:
    "The room before the stacks. Holdings move from acquisition through Pipeline, filing, editorial draft, and publication — then remain under stewardship.",
  lifecycle:
    "Steam acquisition → Pipeline → Filed accession → Editorial draft → Published Library entry → Ongoing stewardship",
  overview: {
    title: "Holdings at a Glance",
    total: "Total Holdings",
    pipeline: "Pipeline",
    filed: "Filed",
    inProgress: "Editorial Draft",
    published: "Published",
  },
  recentAcquisitions: {
    title: "Recent Acquisitions",
    empty: "No recent acquisition activity.",
    importDate: "Entered",
    playtime: "Steam playtime",
    status: "Standing",
  },
  readyToFile: {
    title: "Awaiting Filing",
    note: "Pipeline holdings ordered by playtime, recent play, recent arrival, existing references, and those set aside — never by machine judgment.",
    empty: "No holdings awaiting filing.",
  },
  editorial: {
    title: "Editorial Drafts",
    note: "Documentation currently present in each accession. An archive entry is never finished — only tended.",
    empty: "No accessions currently under editorial work.",
    /** Shown when a section has no curator writing yet. */
    absent: "Not yet entered",
    /** Shown when writing or verification is already on the record. */
    present: "Present in the record",
  },
  batches: {
    title: "Editorial Batches",
    note: "Small bodies of work tended together before publication — closer to preparing an issue than clearing a queue. Prefer five to ten accessions.",
    empty: "No Editorial Batches have been opened.",
    create: "Open a batch",
    creating: "Opening…",
    rename: "Rename",
    renaming: "Renaming…",
    open: "Open batch",
    add: "Add accessions",
    adding: "Adding…",
    remove: "Remove",
    removing: "Removing…",
    publish: "Publish batch",
    publishing: "Publishing…",
    publishConfirm:
      "Publish every accession in this batch to the Bloodsoaked Library? This appends Stewardship History and cannot be undone as a group.",
    nameLabel: "Batch name",
    namePlaceholder: "e.g. Midsummer Issue · Digital Holdings",
    created: "Opened",
    revised: "Last revised",
    count: "Accessions",
    readiness: "Publication readiness",
    eligibleEmpty: "No unbatched Editorial Drafts are available to add.",
    eligibleLead: "Filed Editorial Drafts not yet assigned to a batch.",
    sizeHardCap: "A batch may not exceed twelve accessions.",
    returnToBatch: "Return to batch",
    previousAccession: "← Previous in batch",
    nextAccession: "Next in batch →",
    inBatch: "Editorial Batch",
    fieldPresent: "Present",
    fieldAbsent: "Not yet entered",
  updateIntroduction: "Save introduction",
  updatingIntroduction: "Saving…",
  introductionTitle: "Batch Introduction",
  introductionLead:
    "A short editorial note for this issue. It enters Stewardship History when the batch is published.",
  introductionTitleLabel: "Title",
  introductionTitlePlaceholder: "e.g. First Digital Holdings",
  introductionBodyLabel: "Editorial note",
  introductionBodyPlaceholder:
    "e.g. The first Steam-origin accessions accepted into the Bloodsoaked Library.",
  reviewTitle: "Editorial Review Pass",
  reviewLead:
    "Quiet observations across the batch. Nothing is rewritten automatically — judgment remains with the curator.",
  reviewEmpty: "Add accessions to begin the editorial review.",
  reviewKind: {
    readiness: "Publication readiness",
    documentation: "Documentation",
    authority: "Authority consistency",
    voice: "Editorial voice",
    relationship: "Related works",
  },
  accessionsTitle: "Accessions in this issue",
  readyMark: "Ready for publication.",
  tendingMark: "Still under editorial care.",
  },
  activity: {
    title: "Recent Activity",
    empty: "The logbook is quiet.",
    filed: "Filed",
    steamReconciled: "Steam acquisition",
    published: "Published",
    updated: "Updated",
    curatorNotes: "Curator Notes",
  },
  search: {
    title: "Catalog Lookup",
    placeholder: "Titles, shelf marks, holdings, Steam App IDs…",
    empty: "No holdings or accessions matched that lookup.",
    hint: "Seek Collection holdings, Pipeline records, Library accessions, shelf marks, and Steam App IDs.",
    submit: "Consult",
  },
  actions: {
    file: "File accession",
    filing: "Filing accession…",
    continueEditing: "Continue stewardship",
    openCollection: "Open holding",
    openLibrary: "Open Library accession",
    viewSteam: "Acquisition provenance",
    star: "Set aside",
    unstar: "Release",
    viewPublic: "View on the public shelf",
  },
  lanes: {
    pipeline: "Pipeline",
    filed: "Filed",
    published: "Published",
    "in-progress": "Editorial Draft",
  },
  nav: {
    workbench: "Workbench",
    library: "The Library",
    collection: "The Collection",
  },
  detail: {
    holdingEyebrow: "Collection holding",
    accessionEyebrow: "Library accession",
    hiddenNote:
      "This accession remains off the public shelf. Stewardship continues in the archival record until it is ready to publish.",
    returnLink: "Return to the Workbench",
    provenanceEyebrow: "Acquisition provenance",
    provenanceSteam: "Steam — one source among holdings, not the identity of the archive.",
    lastReconciled: "Last reconciled",
    store: "Store record",
    developers: "Developers",
    publishers: "Publishers",
    release: "Release",
    genres: "Genres",
    artwork: "Preserved artwork",
    standing: "Standing",
    entered: "Entered",
    shelfMark: "Shelf mark",
    lastPlayed: "Last played",
    visibility: "Visibility",
    archivalStatus: "Archival status",
    accessionSource: "Accession source",
    filed: "Filed",
  },
  marks: {
    setAside: "Set aside",
  },
} as const;
